eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 10089
spring:
  application:
    name: lxl
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    

management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false

