eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 10088

spring:
  application:
    name: lxl
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
